services:
  app:
    build: .
    ports:
      - "${APP_PORT:-8082}:8082"
    env_file:
      - .env
    volumes:
      - ./app/data:/app/data
      - ./firebase-adminsdk.json:/app/firebase-adminsdk.json:ro
